const wordlist = require("../../assets/wordlist");
const { AutoGeneratedAlias } = require("./autoAlias");

/*
   4 | "big elk"
   7 | "fun pig"
   8 | "fun elk"
   11 | "big pig"
   12 | "big fun elk"
   15 | "fun big pig"
   */

describe.each`
   index | result
   ${0}  | ${"elk"}
   ${1}  | ${"ant"}
   ${2}  | ${"cow"}
   ${3}  | ${"pig"}
   ${4}  | ${"big elk"}
   ${7}  | ${"fun pig"}
   ${8}  | ${"fun elk"}
   ${11} | ${"big pig"}
`("AutoGeneratedAlias", ({ index, result }) => {
   const autoGeneratedAlias = new AutoGeneratedAlias(index);
   test(`Should return ${result} for index ${index}`, () => {
      expect(autoGeneratedAlias.numericAlias).toEqual(`${index}`);
      expect(autoGeneratedAlias.wordAlias).toEqual(result);
   });
});

describe("AutoGeneratedAlias", () => {
   test("should hold 0 and the first word if given index is 0", () => {
      const autoGeneratedAlias = new AutoGeneratedAlias(0);
      expect(autoGeneratedAlias.numericAlias).toEqual("0");
      expect(autoGeneratedAlias.wordAlias).toEqual("elk");
   });

   test("should hold 18 and a prefixed word if given index is 18", () => {
      const autoGeneratedAlias = new AutoGeneratedAlias(18);
      expect(autoGeneratedAlias.numericAlias).toEqual("18");
      expect(autoGeneratedAlias.wordAlias).toEqual("big elk");
   });

   test("should hold 20 and a prefixed word if given index is 20", () => {
      const autoGeneratedAlias = new AutoGeneratedAlias(20);
      expect(autoGeneratedAlias.numericAlias).toEqual("20");
      expect(autoGeneratedAlias.wordAlias).toEqual("big cow");
   });
});

fdescribe.each`
   index    | result
   ${0}     | ${0}
   ${17}    | ${0}
   ${18}    | ${1}
   ${197}   | ${1}
   ${198}   | ${2}
   ${1997}  | ${2}
   ${1998}  | ${3}
   ${19997} | ${3}
   ${19998} | ${4}
`("_adjectiveCount", ({ index, result }) => {
   test(`should return ${result} for index ${index}`, () => {
      const autoGeneratedAlias = new AutoGeneratedAlias(0);
      expect(autoGeneratedAlias._adjectiveCount(index)).toEqual(result);
   });
});

fdescribe.each`
   index  | result
   ${0}   | ${"elk"}
   ${11}  | ${"bat"}
   ${18}  | ${"big-elk"}
   ${29}  | ${"fun-bat"}
   ${36}  | ${"fun-elk"}
   ${47}  | ${"dry-bat"}
   ${191} | ${"big-bat"}
   ${198} | ${"fun-big-elk"}
   ${209} | ${"dry-fun-bat"}
`("_algorithm", ({ index, result }) => {
   test(`should return ${result} for index ${index}`, () => {
      const autoGeneratedAlias = new AutoGeneratedAlias(0);
      expect(autoGeneratedAlias._algorithm(index)).toEqual(result);
   });
});

// "elk", "ant", "cow", "pig", "dog", "cat", "bee"
// ["big", "fun", "dry", "icy"],
describe.each`
   index  | result
   ${0}   | ${"elk"}
   ${1}   | ${"ant"}
   ${12}  | ${"rat"}
   ${16}  | ${"fly"}
   ${17}  | ${"yak"}
   ${18}  | ${"big-elk"}
   ${19}  | ${"fun-ant"}
   ${27}  | ${"hip-fox"}
   ${28}  | ${"big-hen"}
   ${29}  | ${"fun-bat"}
   ${30}  | ${"dry-rat"}
   ${34}  | ${"rad-fly"}
   ${35}  | ${"pro-yak"}
   ${36}  | ${"fun-elk"}
   ${198} | ${"big-fun-elk"}
   ${199} | ${"fun-dry-ant"}
   ${216} | ${"fun-dry-elk"}
   ${234} | ${"dry-icy-elk"}
   ${252} | ${"icy-mad-elk"}
   ${270} | ${"mad-wet-elk"}
   ${288} | ${"wet-rad-elk"}
   ${306} | ${"rad-pro-elk"}
   ${324} | ${"pro-hot-elk"}
   ${342} | ${"hot-hip-elk"}
   ${360} | ${"hip-big-elk"}
   ${378} | ${"big-dry-elk"}
`("_algorithm", ({ index, result }) => {
   test(`should return ${result} for index ${index}`, () => {
      const autoGeneratedAlias = new AutoGeneratedAlias(0);
      expect(autoGeneratedAlias._algorithm(index)).toEqual(result);
   });
});

describe("foobar", () => {
   test("377", () => {
      const autoGeneratedAlias = new AutoGeneratedAlias(0);
      expect(autoGeneratedAlias._algorithm(377)).toEqual("rad-pro-yak");
   });
   test("378", () => {
      const autoGeneratedAlias = new AutoGeneratedAlias(0);
      expect(autoGeneratedAlias._algorithm(378)).toEqual("big-dry-elk");
   });
});

describe("_algorithm", () => {
   test(`should return for index`, () => {
      const autoGeneratedAlias = new AutoGeneratedAlias(0);
      const arrayToCheck = [];
      for (
         let index = 18;
         index < wordlist.names.length * (wordlist.adjectives.length + 1);
         index++
      ) {
         arrayToCheck.push(autoGeneratedAlias._algorithm(index));
      }
      for (let i = 0; i < arrayToCheck.length; i = i + 18) {
         console.log({ i });
         console.log(arrayToCheck[i]);
      }
      expect(
         arrayToCheck.filter((entry) => entry.includes("hip")).length
      ).toEqual(18);
      expect(
         arrayToCheck.filter((entry) => entry.includes("elk")).length
      ).toEqual(10);
   });
});

describe("_algorithm", () => {
   test(`should return for index`, () => {
      const autoGeneratedAlias = new AutoGeneratedAlias(0);
      const arrayToCheck = [];
      for (
         let index = 198;
         index <
         wordlist.names.length *
            (wordlist.adjectives.length + 1) *
            wordlist.adjectives.length;
         index++
      ) {
         arrayToCheck.push(autoGeneratedAlias._algorithm(index));
      }
      for (let i = 0; i < 260; i = i + 18) {
         console.log({ i });
         console.log(arrayToCheck[i]);
      }
      expect(
         arrayToCheck.filter((entry) => entry.includes("elk")).length
      ).toEqual(100);
   });
});

describe("AutoGeneratedAlias'", () => {
   describe("_findRightIndex", () => {
      test("should return 1 for index 11", () => {
         const result = autoGeneratedAlias._findRightIndex(11);
         expect(result).toEqual(1);
      });
      test("should return 0 for index 20", () => {
         const result = autoGeneratedAlias._findRightIndex(20);
         expect(result).toEqual(0);
      });
      test("should return 9 for index 39", () => {
         const result = autoGeneratedAlias._findRightIndex(39);
         expect(result).toEqual(9);
      });
   });
   describe("_generateNamePrefix", () => {
      test("should return 'big' for index 20", () => {
         const result = autoGeneratedAlias._generateNamePrefix(20);
         expect(result).toEqual("big ");
      });
      test("should return 'big' for index 27", () => {
         const result = autoGeneratedAlias._generateNamePrefix(27);
         expect(result).toEqual("big ");
      });
      test("should return 'fun' for index 28", () => {
         const result = autoGeneratedAlias._generateNamePrefix(36);
         expect(result).toEqual("fun ");
      });
      test("should return 'big big'", () => {
         const result = autoGeneratedAlias._generateNamePrefix(180);
         expect(result).toEqual("big big");
      });
   });
});
