const wordlist = require("../../assets/wordlist");
const { AutoGeneratedAlias } = require("./autoAlias");

/*
   4 | "big elk"
   7 | "fun pig"
   8 | "fun elk"
   11 | "big pig"
   12 | "big fun elk"
   15 | "fun big pig"
   */

describe.each`
   index | result
   ${0}  | ${"elk"}
   ${1}  | ${"ant"}
   ${2}  | ${"cow"}
   ${3}  | ${"pig"}
   ${4}  | ${"big elk"}
   ${7}  | ${"fun pig"}
   ${8}  | ${"fun elk"}
   ${11} | ${"big pig"}
`("AutoGeneratedAlias", ({ index, result }) => {
   const autoGeneratedAlias = new AutoGeneratedAlias(index);
   test(`Should return ${result} for index ${index}`, () => {
      expect(autoGeneratedAlias.numericAlias).toEqual(`${index}`);
      expect(autoGeneratedAlias.wordAlias).toEqual(result);
   });
});

describe("AutoGeneratedAlias", () => {
   test("should hold 0 and the first word if given index is 0", () => {
      const autoGeneratedAlias = new AutoGeneratedAlias(0);
      expect(autoGeneratedAlias.numericAlias).toEqual("0");
      expect(autoGeneratedAlias.wordAlias).toEqual("elk");
   });

   test("should hold 18 and a prefixed word if given index is 18", () => {
      const autoGeneratedAlias = new AutoGeneratedAlias(18);
      expect(autoGeneratedAlias.numericAlias).toEqual("18");
      expect(autoGeneratedAlias.wordAlias).toEqual("big elk");
   });

   test("should hold 20 and a prefixed word if given index is 20", () => {
      const autoGeneratedAlias = new AutoGeneratedAlias(20);
      expect(autoGeneratedAlias.numericAlias).toEqual("20");
      expect(autoGeneratedAlias.wordAlias).toEqual("big cow");
   });
});

fdescribe("_algorithm", () => {
   const autoGeneratedAlias = new AutoGeneratedAlias(0);
   for (let index = 0; index < 4; index++) {
      expect(autoGeneratedAlias._algorithm(index)).toEqual(
         wordlist.names[index]
      );
   }
});

describe("AutoGeneratedAlias'", () => {
   describe("_findRightIndex", () => {
      test("should return 1 for index 11", () => {
         const result = autoGeneratedAlias._findRightIndex(11);
         expect(result).toEqual(1);
      });
      test("should return 0 for index 20", () => {
         const result = autoGeneratedAlias._findRightIndex(20);
         expect(result).toEqual(0);
      });
      test("should return 9 for index 39", () => {
         const result = autoGeneratedAlias._findRightIndex(39);
         expect(result).toEqual(9);
      });
   });
   describe("_generateNamePrefix", () => {
      test("should return 'big' for index 20", () => {
         const result = autoGeneratedAlias._generateNamePrefix(20);
         expect(result).toEqual("big ");
      });
      test("should return 'big' for index 27", () => {
         const result = autoGeneratedAlias._generateNamePrefix(27);
         expect(result).toEqual("big ");
      });
      test("should return 'fun' for index 28", () => {
         const result = autoGeneratedAlias._generateNamePrefix(36);
         expect(result).toEqual("fun ");
      });
      test("should return 'big big'", () => {
         const result = autoGeneratedAlias._generateNamePrefix(180);
         expect(result).toEqual("big big");
      });
   });
});
