version: 2.1


version: 2
jobs:
  build:
    docker:
      - image: "circleci/node:8.9.0"
    steps:
      - checkout
      - run: echo "$(node -v)"
workflows:
  version: 2
  build:
    jobs:
      - build
