version: 2.1
jobs:
  build:
    docker:
      - image: "circleci/node:10.9.0"
    steps:
      - checkout
      - run: npm ci && npm run build-darwin-binary
workflows:
  version: 2
  build:
    jobs:
      - build
