version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: "circleci/node:10.9.0"

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm ci && sudo npm link && project-butler -s && eval "$(project-butler -s)" && p
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
               - master # list of branches to build